all:
	dotnet build
	dotnet run

build:
	dotnet build

run:
	dotnet run

prepare:
	dotnet add package Grpc.Net.Client
	dotnet add package Google.Protobuf
	dotnet add package Grpc.Tools
	dotnet add package System.ServiceModel.Http
	dotnet add package GraphQL.Client
	dotnet add package GraphQL.Client.Serializer.Newtonsoft
	dotnet add package Newtonsoft.Json